# Generated by Django 3.0.6 on 2020-06-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_auto_20200607_1706'),
        ('users', '0005_auto_20200522_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='actions.Contact', to='users.Profile'),
        ),
    ]
