# Generated by Django 3.0.6 on 2020-06-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0011_auto_20200608_1923'),
        ('users', '0011_remove_profile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='actions.Contact', to='users.Profile'),
        ),
    ]
