# Generated by Django 3.0.6 on 2020-06-08 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_profile_following'),
        ('actions', '0019_auto_20200608_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='users.Profile'),
        ),
    ]
