# Generated by Django 3.0.6 on 2020-05-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_like_unlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, height_field=200, upload_to='uploads/% Y/% m/% d/', width_field=100),
        ),
    ]
