# Generated by Django 3.0.6 on 2020-06-06 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_remove_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unlike',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='unlike',
            name='post',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Unlike',
        ),
    ]
