# Generated by Django 3.0.6 on 2020-06-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_action'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Action',
        ),
    ]
