# Generated by Django 3.0.6 on 2020-06-06 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0018_post_total_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Action',
        ),
    ]
